### ISSUE TITLE
LFW dataset used

### ISSUE THREAD

**Issue by Source82** [grib0ed0v/face_recognition.pytorch#5]
Please which of the LFW images were used ? is it **All Images** or **All Images - alligned with deep funelling**?

**Comment by grib0ed0v** [comment]
@Source82 hi! It's **All images** + [facial landmark file](https://github.com/clcarwin/sphereface_pytorch/blob/master/data/lfw_landmark.txt). The code does 5-point alignment when you pass the landmark file, otherwise - no alignment.

**Comment by Source82** [comment]
Thanks

**Comment by Source82** [comment]
I can confirm that the landmarks correspond t the 250 x 250 deep funneled crops accessible here http://vis-www.cs.umass.edu/lfw/lfw-deepfunneled.tgz
